version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 2

  gateway:
    build: src/gateway-service/
    container_name: gateway
    restart: on-failure
    ports:
      - "8080:8080"

  flight:
    build: src/flight-service/
    container_name: flight
    restart: on-failure
    ports:
      - "8060:8060"

  privilege:
    build: src/bonus-service/
    container_name: privilege
    restart: on-failure
    ports:
      - "8050:8050"

  ticket:
    build: src/ticket-service/
    container_name: ticket
    restart: on-failure
    ports:
      - "8070:8070"


volumes:
  db-data: