apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
  selector:
    service: {{ .Chart.Name }}