flight:
  service:
    type: NodePort
    port: 8070
    nodePort: 30070
    image: vuquang142k/flight-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

bonus:
  service:
    type: NodePort
    port: 8060
    nodePort: 30060
    image: vuquang142k/bonus-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

ticket:
  service:
    type: NodePort
    port: 8050
    nodePort: 30050
    image: vuquang142k/ticket-service:latest
    env:
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres

gateway:
   service:
    type: NodePort
    port: 8080
    nodePort: 30000
    image: vuquang142k/gateway-service:latest
    isGateway: true
    env:
      FLIGHT_SERVICE_HOST: flight.vuquang142k.svc.cluster.local
      FLIGHT_SERVICE_PORT: 8070
      BONUS_SERVICE_HOST: bonus.vuquang142k.svc.cluster.local
      BONUS_SERVICE_PORT: 8060
      TICKET_SERVICE_HOST: ticket.vuquang142k.svc.cluster.local
      TICKET_SERVICE_PORT: 8050