name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        
      - name: Build images
        timeout-minutes: 10
        run: |
          docker compose build
          
      - name: Run containers
        timeout-minutes: 10
        run: |
          docker compose up -d
          sudo chmod +x ./scripts/wait-script.sh
          sudo chmod +x ./scripts/wait-for.sh
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050,5432
      
      - name: Wait 15s
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build docker images
        run: |
          docker build ./src/bonus-service/ -t vuquang142k/bonus-service:latest
          docker build ./src/flight-service/ -t vuquang142k/flight-service:latest
          docker build ./src/gateway-service/ -t vuquang142k/gateway-service:latest
          docker build ./src/ticket-service/ -t vuquang142k/ticket-service:latest
      
      - name: Push the images to Docker Hub
        run: |
          docker push vuquang142k/flight-service:latest 
          docker push vuquang142k/bonus-service:latest
          docker push vuquang142k/ticket-service:latest
          docker push vuquang142k/gateway-service:latest
      
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
  
      - name: Check Minikube Cluster
        run: |
          kubectl get pods -A
  
      - name: Create Namespace in Cluster
        run: |
          kubectl create namespace vuquang142k

      - name: Deploy DB and services
        run: |
          kubectl get namespace
          cd k8s
          echo "------------------Deploy Postgres DB------------------"
          helm delete postgres --namespace vuquang142k --ignore-not-found
          helm install -n vuquang142k postgres ./postgres_db
          echo "------------------Deploy Services------------------"
          helm delete reserv --namespace vuquang142k --ignore-not-found
          helm install -n vuquang142k reserv ./services

      - name: Wait 30s
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Get all resources from namespace vuquang142k in Cluster
        run: |
          kubectl get all -n vuquang142k
          kubectl get services -n vuquang142k

      - name: Setup Ingress
        run: |
          cd k8s/networking
          kubectl apply -f ingress.yaml
          kubectl get ingress
          sudo echo "$(minikube ip) myapp.local" | sudo tee -a /etc/hosts
          URL=$(minikube service flight -n vuquang142k --url)

      - name: Setup Postman environment
        run: |
          cd v1/postman
          echo '[
            {"key": "serviceUrl", "value": "http://${{ secrets.PROD_HOST }}:${{ secrets.PROD_PORT }}"},
            {"key": "tokenUrl", "value": "${{ secrets.KC_HOST }}"},
            {"key": "username", "value": "${{ secrets.KC_USERNAME }}"},
            {"key": "password", "value": "${{ secrets.KC_PASSWORD }}"},
            {"key": "clientId", "value": "${{ secrets.KC_CLIENT_ID }}"},
            {"key": "clientSecret", "value": "${{ secrets.KC_CLIENT_SECRET }}"}
          ]' > environment.json

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
